version: '3'
services:
  nextjs:
    build: /root/Insignia-Images
    container_name: nextjs
    ports:
      - "3005:3005"
    restart: always

  nextjs-project2:
    build: /root/Virtuality-Dashboard
    container_name: nextjs-project2
    ports:
      - "3001:3001"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl  # Path to the directory containing your Cloudflare SSL certificates
    depends_on:
      - nextjs
      - nextjs-project2
    restart: always

networks:
  default:
    driver: bridge

